lexer grammar Token;
NUMBER : [0-9]+ ;
DOUBLE : [0-9]+'.'[0-9]+ ;
ID : [a-zA-Z0-9_]+ ;
ASSIGN: '=';
COMMA: ',';
PLUS: '+';
MINUS: '-';
TIMES: '*';
POW:'^';
DIVIDE: '/';
LPAREN: '(';
RPAREN: ')';
LBRACE: '{';
RBRACE: '}';
SEMICOLON: ';';
LSQUAREBRACE: '[';
RSQUAREBRACE: ']';
OP_RELACIONAL: '>'|'<'|'>='|'<='|'!=';
STRING : '"' .*? '"' ;
WS : [ \t\r\n]+ -> skip ;